name: open_show_runner
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  flex_color_scheme: ^4.2.0
  google_fonts: ^2.3.1
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.0

  # State Management
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3

  # Cue System
  osc: ^1.0.0
  just_audio: ^0.9.20
  file_picker: ^4.5.0

  # System
  flutter_local_notifications: ^9.4.0
  connectivity_plus: ^2.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
